<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-78H043L" ignored="0" name="Default test" tests="89" failures="16" timestamp="2020-10-15T01:26:34 IST" time="95.114" errors="0">
  <testcase name="TestAddCity" time="3.569" classname="com.temp.test.TestsWeather"/>
  <testcase name="TestPrintCities" time="0.002" classname="com.temp.test.TestsWeather"/>
  <testcase name="unCheckCities" time="2.784" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="8.497" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="8.52" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Ajmer: The Actual temp is 23.670013 and expected is 34.0 expected [34.0] but found [23.670013]">
      <![CDATA[java.lang.AssertionError: For city Ajmer: The Actual temp is 23.670013 and expected is 34.0 expected [34.0] but found [23.670013]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:744)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:181)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="8.544" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="8.567" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="8.591" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="8.619" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="8.648" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="8.673" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="8.695" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="8.834" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="0.773" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.NumberFormatException" message="For input string: &amp;quot;&amp;quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: ""
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:592)
at java.lang.Integer.valueOf(Integer.java:766)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:155)
at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="5.912" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="5.963" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="5.97" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="5.968" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="5.969" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="5.965" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="5.958" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Chandigarh: The Actual temp is 21.720001 and expected is 34.0 expected [34.0] but found [21.720001]">
      <![CDATA[java.lang.AssertionError: For city Chandigarh: The Actual temp is 21.720001 and expected is 34.0 expected [34.0] but found [21.720001]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:744)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:181)
at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="6.686" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.972" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Dehra Dun: The Actual temp is 20.940002 and expected is 31.0 expected [31.0] but found [20.940002]">
      <![CDATA[java.lang.AssertionError: For city Dehra Dun: The Actual temp is 20.940002 and expected is 31.0 expected [31.0] but found [20.940002]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:744)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:181)
at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="11.357" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.445" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.445" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Ganganagar: The Actual temp is 24.559998 and expected is 36.0 expected [36.0] but found [24.559998]">
      <![CDATA[java.lang.AssertionError: For city Ganganagar: The Actual temp is 24.559998 and expected is 36.0 expected [36.0] but found [24.559998]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:744)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:181)
at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="6.421" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.373" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.466" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.466" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="7.168" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="7.802" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="8.26" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.333" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.516" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.431" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.513" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Imphal: The Actual temp is 18.649994 and expected is 29.0 expected [29.0] but found [18.649994]">
      <![CDATA[java.lang.AssertionError: For city Imphal: The Actual temp is 18.649994 and expected is 29.0 expected [29.0] but found [18.649994]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:744)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:181)
at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="6.515" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.998" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Jalandhar: The Actual temp is 22.01001 and expected is 34.0 expected [34.0] but found [22.01001]">
      <![CDATA[java.lang.AssertionError: For city Jalandhar: The Actual temp is 22.01001 and expected is 34.0 expected [34.0] but found [22.01001]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:744)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:181)
at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="7.164" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Jammu: The Actual temp is 21.0 and expected is 34.0 expected [34.0] but found [21.0]">
      <![CDATA[java.lang.AssertionError: For city Jammu: The Actual temp is 21.0 and expected is 34.0 expected [34.0] but found [21.0]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:744)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:181)
at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="6.824" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.46" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.391" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="10.127" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.449" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.425" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.488" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="5.875" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="7.489" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="7.629" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="2.228" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.NumberFormatException" message="For input string: &amp;quot;&amp;quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: ""
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:592)
at java.lang.Integer.valueOf(Integer.java:766)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:155)
at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="7.387" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="9.712" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Ludhiana: The Actual temp is 22.140015 and expected is 34.0 expected [34.0] but found [22.140015]">
      <![CDATA[java.lang.AssertionError: For city Ludhiana: The Actual temp is 22.140015 and expected is 34.0 expected [34.0] but found [22.140015]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:744)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:181)
at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="6.175" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.145" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.14" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.145" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="7.393" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="7.75" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.981" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.893" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.885" classname="com.temp.test.TestsWeather">
    <failure type="org.json.JSONException" message="JSONObject[&amp;quot;main&amp;quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["main"] not found.
at org.json.JSONObject.get(JSONObject.java:572)
at org.json.JSONObject.getJSONObject(JSONObject.java:782)
at com.temp.api.ApiUtils.getTemp(ApiUtils.java:94)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:167)
at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="6.44" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.323" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.372" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.363" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="7.043" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Patiala: The Actual temp is 22.580017 and expected is 34.0 expected [34.0] but found [22.580017]">
      <![CDATA[java.lang.AssertionError: For city Patiala: The Actual temp is 22.580017 and expected is 34.0 expected [34.0] but found [22.580017]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:744)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:181)
at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="6.577" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="7.163" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.992" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="7.039" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="7.317" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="7.11" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="7.09" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="7.167" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="3.677" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.NumberFormatException" message="For input string: &amp;quot;&amp;quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: ""
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:592)
at java.lang.Integer.valueOf(Integer.java:766)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:155)
at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="7.245" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Saharanpur: The Actual temp is 22.140015 and expected is 33.0 expected [33.0] but found [22.140015]">
      <![CDATA[java.lang.AssertionError: For city Saharanpur: The Actual temp is 22.140015 and expected is 33.0 expected [33.0] but found [22.140015]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:744)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:181)
at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="4.276" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.NumberFormatException" message="For input string: &amp;quot;&amp;quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: ""
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:592)
at java.lang.Integer.valueOf(Integer.java:766)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:155)
at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="8.592" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="7.904" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="5.941" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.174" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Srinagar: The Actual temp is 11.860016 and expected is 26.0 expected [26.0] but found [11.860016]">
      <![CDATA[java.lang.AssertionError: For city Srinagar: The Actual temp is 11.860016 and expected is 26.0 expected [26.0] but found [11.860016]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:744)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:181)
at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="5.647" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="5.708" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="5.754" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="5.993" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.873" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.872" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="4.989" classname="com.temp.test.TestsWeather"/>
</testsuite> <!-- Default test -->
