<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-78H043L" name="com.temp.test.TestsWeather" tests="89" failures="20" timestamp="2020-10-15T05:18:28 IST" time="574.761" errors="6">
  <testcase name="getTemp" time="5.382" classname="com.temp.test.TestsWeather">
    <error type="java.lang.NumberFormatException" message="For input string: &quot;&quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: ""
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:592)
at java.lang.Integer.valueOf(Integer.java:766)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:183)
at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- getTemp -->
  <system-out/>
  <testcase name="getTemp" time="6.012" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="unCheckCities" time="2.890" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="7.224" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Patiala: The Actual temp is 20.589996 and expected is 34.0 expected [34.0] but found [20.589996]">
      <![CDATA[java.lang.AssertionError: For city Patiala: The Actual temp is 20.589996 and expected is 34.0 expected [34.0] but found [20.589996]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:744)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <system-out/>
  <testcase name="getTemp" time="7.058" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Imphal: The Actual temp is 17.74002 and expected is 29.0 expected [29.0] but found [17.74002]">
      <![CDATA[java.lang.AssertionError: For city Imphal: The Actual temp is 17.74002 and expected is 29.0 expected [29.0] but found [17.74002]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:744)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <system-out/>
  <testcase name="getTemp" time="6.033" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="7.056" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="7.165" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="6.387" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="7.457" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="6.442" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="7.199" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Ganganagar: The Actual temp is 22.149994 and expected is 36.0 expected [36.0] but found [22.149994]">
      <![CDATA[java.lang.AssertionError: For city Ganganagar: The Actual temp is 22.149994 and expected is 36.0 expected [36.0] but found [22.149994]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:744)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <system-out/>
  <testcase name="getTemp" time="6.421" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="8.514" classname="com.temp.test.TestsWeather">
    <error type="java.util.ConcurrentModificationException">
      <![CDATA[java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
at java.util.ArrayList$Itr.next(ArrayList.java:859)
at com.relevantcodes.extentreports.model.Test.trackLastRunStatus(Test.java:389)
at com.relevantcodes.extentreports.ExtentTest.log(ExtentTest.java:102)
at com.relevantcodes.extentreports.ExtentTest.log(ExtentTest.java:188)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:220)
at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- getTemp -->
  <system-out/>
  <testcase name="getTemp" time="6.354" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="6.420" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="TestPrintCities" time="0.001" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="6.095" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="10.947" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Dehra Dun: The Actual temp is 20.330017 and expected is 31.0 expected [31.0] but found [20.330017]">
      <![CDATA[java.lang.AssertionError: For city Dehra Dun: The Actual temp is 20.330017 and expected is 31.0 expected [31.0] but found [20.330017]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:744)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <system-out/>
  <testcase name="getTemp" time="5.920" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="7.093" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Panipat: The Actual temp is 21.709991 and expected is 33.0 expected [33.0] but found [21.709991]">
      <![CDATA[java.lang.AssertionError: For city Panipat: The Actual temp is 21.709991 and expected is 33.0 expected [33.0] but found [21.709991]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:744)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <system-out/>
  <testcase name="getTemp" time="7.021" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Srinagar: The Actual temp is 10.160004 and expected is 26.0 expected [26.0] but found [10.160004]">
      <![CDATA[java.lang.AssertionError: For city Srinagar: The Actual temp is 10.160004 and expected is 26.0 expected [26.0] but found [10.160004]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:744)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <system-out/>
  <testcase name="getTemp" time="5.950" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="6.342" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="5.819" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Moradabad: The Actual temp is 21.399994 and expected is 32.0 expected [32.0] but found [21.399994]">
      <![CDATA[java.lang.AssertionError: For city Moradabad: The Actual temp is 21.399994 and expected is 32.0 expected [32.0] but found [21.399994]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:744)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <system-out/>
  <testcase name="getTemp" time="6.139" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="4.074" classname="com.temp.test.TestsWeather">
    <error type="java.lang.NumberFormatException" message="For input string: &quot;&quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: ""
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:592)
at java.lang.Integer.valueOf(Integer.java:766)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:183)
at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- getTemp -->
  <system-out/>
  <testcase name="getTemp" time="6.472" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="6.294" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="7.118" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="TestAddCity" time="1.171" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="8.090" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Amritsar: The Actual temp is 18.0 and expected is 34.0 expected [34.0] but found [18.0]">
      <![CDATA[java.lang.AssertionError: For city Amritsar: The Actual temp is 18.0 and expected is 34.0 expected [34.0] but found [18.0]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:744)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <system-out/>
  <testcase name="getTemp" time="7.253" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Chandigarh: The Actual temp is 21.059998 and expected is 34.0 expected [34.0] but found [21.059998]">
      <![CDATA[java.lang.AssertionError: For city Chandigarh: The Actual temp is 21.059998 and expected is 34.0 expected [34.0] but found [21.059998]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:744)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <system-out/>
  <testcase name="getTemp" time="7.138" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="6.335" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="3.285" classname="com.temp.test.TestsWeather">
    <error type="java.lang.NumberFormatException" message="For input string: &quot;&quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: ""
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:592)
at java.lang.Integer.valueOf(Integer.java:766)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:183)
at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- getTemp -->
  <system-out/>
  <testcase name="getTemp" time="10.496" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="6.959" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="7.300" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Jammu: The Actual temp is 20.0 and expected is 34.0 expected [34.0] but found [20.0]">
      <![CDATA[java.lang.AssertionError: For city Jammu: The Actual temp is 20.0 and expected is 34.0 expected [34.0] but found [20.0]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:744)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <system-out/>
  <testcase name="getTemp" time="7.025" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="5.770" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="7.527" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Hisar: The Actual temp is 22.869995 and expected is 35.0 expected [35.0] but found [22.869995]">
      <![CDATA[java.lang.AssertionError: For city Hisar: The Actual temp is 22.869995 and expected is 35.0 expected [35.0] but found [22.869995]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:744)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <system-out/>
  <testcase name="getTemp" time="6.584" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Muzaffarnagar: The Actual temp is 21.0 and expected is 33.0 expected [33.0] but found [21.0]">
      <![CDATA[java.lang.AssertionError: For city Muzaffarnagar: The Actual temp is 21.0 and expected is 33.0 expected [33.0] but found [21.0]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:744)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <system-out/>
  <testcase name="getTemp" time="6.651" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="6.363" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="7.634" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="6.415" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Bikaner: The Actual temp is 25.630005 and expected is 36.0 expected [36.0] but found [25.630005]">
      <![CDATA[java.lang.AssertionError: For city Bikaner: The Actual temp is 25.630005 and expected is 36.0 expected [36.0] but found [25.630005]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:744)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <system-out/>
  <testcase name="getTemp" time="6.531" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="7.521" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="7.811" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="7.806" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Ajmer: The Actual temp is 23.559998 and expected is 34.0 expected [34.0] but found [23.559998]">
      <![CDATA[java.lang.AssertionError: For city Ajmer: The Actual temp is 23.559998 and expected is 34.0 expected [34.0] but found [23.559998]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:744)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <system-out/>
  <testcase name="getTemp" time="6.761" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="6.053" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="5.891" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="6.928" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="5.994" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="5.818" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="6.427" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="6.266" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="6.390" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="6.129" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="6.329" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="6.462" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Jalandhar: The Actual temp is 20.070007 and expected is 34.0 expected [34.0] but found [20.070007]">
      <![CDATA[java.lang.AssertionError: For city Jalandhar: The Actual temp is 20.070007 and expected is 34.0 expected [34.0] but found [20.070007]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:744)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <system-out/>
  <testcase name="getTemp" time="5.170" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="6.508" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="6.369" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Karnal: The Actual temp is 20.700012 and expected is 33.0 expected [33.0] but found [20.700012]">
      <![CDATA[java.lang.AssertionError: For city Karnal: The Actual temp is 20.700012 and expected is 33.0 expected [33.0] but found [20.700012]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:744)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <system-out/>
  <testcase name="getTemp" time="6.465" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Saharanpur: The Actual temp is 20.839996 and expected is 33.0 expected [33.0] but found [20.839996]">
      <![CDATA[java.lang.AssertionError: For city Saharanpur: The Actual temp is 20.839996 and expected is 33.0 expected [33.0] but found [20.839996]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:744)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <system-out/>
  <testcase name="getTemp" time="6.566" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="6.997" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="6.356" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Jodhpur: The Actual temp is 25.720001 and expected is 36.0 expected [36.0] but found [25.720001]">
      <![CDATA[java.lang.AssertionError: For city Jodhpur: The Actual temp is 25.720001 and expected is 36.0 expected [36.0] but found [25.720001]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:744)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <system-out/>
  <testcase name="getTemp" time="7.244" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="6.463" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Ludhiana: The Actual temp is 20.200012 and expected is 34.0 expected [34.0] but found [20.200012]">
      <![CDATA[java.lang.AssertionError: For city Ludhiana: The Actual temp is 20.200012 and expected is 34.0 expected [34.0] but found [20.200012]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:744)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <system-out/>
  <testcase name="getTemp" time="6.509" classname="com.temp.test.TestsWeather">
    <error type="org.json.JSONException" message="JSONObject[&quot;main&quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["main"] not found.
at org.json.JSONObject.get(JSONObject.java:572)
at org.json.JSONObject.getJSONObject(JSONObject.java:782)
at com.temp.api.ApiUtils.getTemp(ApiUtils.java:94)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:198)
at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- getTemp -->
  <system-out/>
  <testcase name="getTemp" time="7.271" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="6.676" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="7.185" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Gorakhpur: The Actual temp is 21.830017 and expected is 34.0 expected [34.0] but found [21.830017]">
      <![CDATA[java.lang.AssertionError: For city Gorakhpur: The Actual temp is 21.830017 and expected is 34.0 expected [34.0] but found [21.830017]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:744)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getTemp -->
  <system-out/>
  <testcase name="getTemp" time="6.527" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="5.906" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="6.495" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="6.561" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="6.552" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="6.982" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="5.920" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="7.154" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="7.642" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="7.855" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="1.847" classname="com.temp.test.TestsWeather">
    <error type="java.lang.NumberFormatException" message="For input string: &quot;&quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: ""
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:592)
at java.lang.Integer.valueOf(Integer.java:766)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:183)
at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- getTemp -->
  <system-out/>
  <testcase name="getTemp" time="6.561" classname="com.temp.test.TestsWeather"/>
  <system-out/>
  <testcase name="getTemp" time="6.568" classname="com.temp.test.TestsWeather"/>
  <system-out/>
</testsuite> <!-- com.temp.test.TestsWeather -->
